language: rust
env:
  global:
    - PROJECT_NAME: termcolor
    - RUST_BACKTRACE: full
matrix:
  fast_finish: true
  include:
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu
    # Minimum Rust supported channel. We enable these to make sure ripgrep
    # continues to work on the advertised minimum Rust version.
    - os: linux
      rust: 1.20.0
      env: TARGET=x86_64-unknown-linux-gnu
install: ci/install.sh
script: ci/script.sh
branches:
  only:
    # Pushes and PR to the master branch
    - master
notifications:
  email:
    on_success: never
