[package]
name = "ripgrep"
version = "0.1.8"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = """
Line oriented search tool using Rust's regex library. Combines the raw
performance of grep with the usability of the silver searcher.
"""
documentation = "https://github.com/BurntSushi/ripgrep"
homepage = "https://github.com/BurntSushi/ripgrep"
repository = "https://github.com/BurntSushi/ripgrep"
readme = "README.md"
keywords = ["regex", "grep", "egrep", "search", "pattern"]
license = "Unlicense/MIT"

[[bin]]
bench = false
path = "src/main.rs"
name = "rg"

[[test]]
name = "integration"
path = "tests/tests.rs"

[dependencies]
deque = "0.3"
docopt = "0.6"
env_logger = "0.3"
fnv = "1.0"
grep = { version = "0.1.1", path = "grep" }
lazy_static = "0.2"
libc = "0.2"
log = "0.3"
memchr = "0.1"
memmap = "0.2"
num_cpus = "1"
regex = "0.1.76"
rustc-serialize = "0.3"
term = "0.4"
walkdir = "0.1"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2"
winapi = "0.2"

[features]
simd-accel = ["regex/simd-accel"]

[dev-dependencies]
glob = "0.2"

[profile.release]
debug = true
panic = "abort"
